### ISSUE TITLE
Instalation on fresh mac cannot be finished

### ISSUE THREAD

**Issue by dbadura** [pkosiec/terminer#39]
I got fresh mac installation and I had to change following thing, so as to install terminer:
* Add sudo to download command: 
`curl -sfL https://raw.githubusercontent.com/pkosiec/terminer/master/install.sh | sh -s -- -b /usr/local/bin` -> 
`curl -sfL https://raw.githubusercontent.com/pkosiec/terminer/master/install.sh | sudo sh -s -- -b /usr/local/bin`.

After installing zsh, by using command `terminer install zsh-starter`, I got messages `env: python2: No such file or directory` on console. So I had to set:
* link python after entering zsh. I commited: `sudo ln -sf /usr/bin/python2.7 /usr/local/bin/python2`.

**Comment by pkosiec** [comment]
Hi @dbadura, thank you for the issue.

So actually there are two issues:
- bug in ZSH recipe
- bug in docs (Mac installation)

I will fix that in the following weeks.

**Comment by pkosiec** [comment]
Hi, sorry for a long delay. The bug should be fixed in https://github.com/pkosiec/terminer/commit/d52a8d17ef937caf6fcbde00d7c9cca6507de8e8
I tested in on brand-new Mac. Cheers!
